server:
  port: 8090
  forward-headers-strategy: native
  error:
    include-message: always
  address: 0.0.0.0
spring:
  devtools:
    restart:
      eanbled: false
  mvc:
    pathmatch:
      use-suffix-pattern: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  output:
    ansi:
      enabled: always
  datasource:
    type: com.zaxxer.hikari.HikariDataSource

    # H2 database configuration.
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:${halo.work-dir}/db/halo
#    username: admin
#    password: 123456
#      MySQL database configuration.
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://222.207.18.155:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 654487508
    hikari:
      maximum-pool-size: 50
      idle-timeout: 0
      pool-name: myPool
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    format-sql: true
    use-sql-comments: true
  flyway:
    enabled: false
  servlet:
    multipart:
      max-file-size: 10240MB
      max-request-size: 10240MB
      resolve-lazily: true
  freemarker:
    suffix: .ftl
    settings:
      auto_import: /common/macro/global_macro.ftl as global
    template-loader-path:
      - file:///${halo.work-dir}/templates/
      - classpath:/templates/
    expose-spring-macro-helpers: false
management:
  endpoints:
    web:
      base-path: /api/admin/actuator
      exposure:
        include: [ 'httptrace', 'metrics', 'env', 'logfile', 'health' ]
logging:
  level:
    run.halo.app: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.eclipse.jetty.server.HttpChannel: ERROR
  file:
    path: ${halo.work-dir}/logs

springfox:
  documentation:
    enabled: false

halo:
  download-timeout: 5m
  cache: memory
  work-dir: ${user.home}/halo/